version: '2.4'

services:

  # database for filament_manager plugin (comment if not needed, you may also remove this plugin from printers dockerfiles)
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 172.18.0.2
    restart: always
    environment:
      POSTGRES_USER: octoprint
      POSTGRES_PASSWORD: octoprint
      POSTGRES_DB: octoprint_filamentmanager
    ports:
      - 5432:5432

  # database administrator on port 4000 for filament_manager (comment if not needed)
  dbadmin:
    image: adminer
    restart: always
    ports:
      - 4000:8080

  # printer #1 on port 3001
  ender3v2-00:
    build: octoprint/ender3v2
    image: octoprint/ender3v2
    volumes:
      - ender3v2-00-data:/octoprint
    devices:
      - /dev/hub01:/dev/ttyUSB
      - /dev/hub02_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.11
    restart: always
    ports:
      - 3001:80

  # printer #2 on port 3002
  ender3v2-01:
    build: octoprint/ender3v2
    image: octoprint/ender3v2
    volumes:
      - ender3v2-01-data:/octoprint
    devices:
      - /dev/hub03:/dev/ttyUSB
      - /dev/hub04_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.12
    restart: always
    ports:
      - 3002:80

  # printer #3 on port 3003
  cr10v3-00:
    build: octoprint/default
    image: octoprint/default
    volumes:
      - cr10v3-00-data:/octoprint
    devices:
      - /dev/hub05:/dev/ttyUSB
      - /dev/hub06_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.13
    restart: always
    ports:
      - 3003:80

  # printer #4 on port 3004
  cr10max-00:
    build: octoprint/default
    image: octoprint/default
    volumes:
      - cr10max-00-data:/octoprint
    devices:
      - /dev/hub07:/dev/ttyUSB
      - /dev/hub08_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.14
    restart: always
    ports:
      - 3004:80

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  db-data:
    driver: local
  ender3v2-00-data:
    driver: local
  ender3v2-01-data:
    driver: local
  cr10v3-00-data:
    driver: local
  cr10max-00-data:
    driver: local
    